   - Define libraryDependencies in a separate file 
   - Split test and main dependencies
   - Consider using Scopes like "Test" instead of manually excluding 
   - Define common settings like resolvers in a separate file to reduce duplication