   - Use type constraints like type = list(string) instead of type = "list"
   - Use dynamic blocks instead of count where possible
   - Combine private/public subnet variables using objects/maps
   - Consolidate route table variables 